#!/usr/bin/env bash
cat global.js log.js util.js $.js module.js MObject.js  MClass.js Base.js is.js MemberSpec.js protocol.js option.js overload.js MEvent.js MInspect.js  > zero_all.js
gjc zero_all.js
