(function(e){function f(){this.__member={}}function d(a,b){var c=arguments.callee,d=typeof a;if("object"==d)for(var e in a)c.set(e,a[e]);else"string"==d&&c.set(a,b);return c}f.prototype={set:function(a,b){this.get(a)&&this.destroy(a);this.__member[a]=b;this.__onChange();return this},__onChange:function(){this.all=this.__getEvalCode()},get:function(a){return this.__member[a]},list:function(){var a=[],b;for(b in this.__member)a.push(b);return a},destroy:function(a){a in this.__member&&(delete this.__member[a],
this.__onChange())},exportTo:function(a,b){"string"==typeof a&&(a=[a]);var c=this;(a||this.list()).forEach(function(a){b[a]=c.get(a)})},run:function(a){var b=a.__args;b||(b=(b=a.toString().match(/\((.*)?\)/))&&b[1]?b[1].replace(/ /g,"").split(","):[],a.__args=b);0===b.length&&(b=this.list(),a=a.toString(),a=a.substr(a.indexOf("{")),a=eval("(function(){ return function("+b.join(",")+")"+a+"})()"));for(var c=[],d=0,e=b.length;d<e;d++)c.push(this.get(b[d]));a.apply({},c);return this},__getEvalCode:function(){var a=
[];this.list().forEach(function(b){a.push(b+"=$global.get('"+b+"')")});return"var "+a.join(",")+";"}};var b=new f,c;for(c in b)d[c]=b[c];b={};b.VariableManager=f;d("z",b);e.$global=d;e.$run=function(a){var b={};a.apply(b,arguments);return b}})(this);
$run(function(){eval($global.all);var e=function(){};e.info=function(){};e.warn=function(){};e.debug=function(){};e.error=function(){};if("undefined"!=typeof console){"function"==typeof console.log&&(e=function(b){console.log(b)});for(var f=["info","warn","error","debug"],d=f.length;d--;){var b=f[d-1];"function"==typeof console[b]&&(e[b]=function(b){return function(a){console[b](a)}}(b))}}$global("$log",e)});
$run(function(){function e(a,b){if(b instanceof Array)for(var c=0,d=b.length;c<d;c++)e(a,b[c]);else if(a.indexOf)-1==a.indexOf(b)&&a.push(b);else{for(c=a.length;c--;)if(a[c]==b)return;a.push(b)}}function f(a,b,c,d){for(;a;){if(!1===c.apply(d,[a]))return!1;a=a[b]}return!0}function d(){var a=arguments,b=a[0],c=typeof a[1];"string"==c?(c=a[1],a=a[2]||{},!a.hasOwnProperty("writable")&&(!a.set&&!a.get)&&(a.writable=!0),Object.defineProperty(b,c,a)):"object"==c&&z._everyKey(a[1],function(a,c){d(b,a,c)})}
function b(){return b.caller.apply(this,arguments)}eval($global.all);var c=void 0!=={}.__proto__?function(a,b,c){return f(a.__proto__,"__proto__",b,c)}:function(a,b,c){var d=a.constructor.prototype;d==a&&(d=a.constructor.baseProto);for(;d;){if(!1===b.apply(c,[d]))return!1;d=d.constructor.baseProto}if(a.constructor!==Object&&!1===b.apply(c,[Object.prototype]))return!1};z._every=function(a,b,c){if(!a)return!0;for(var d=0,e=a.length;d<e;d++)if(!1===b.apply(c,[a[d]]))return!1;return!0};z._everyKey=function(a,
b,c){if("function"!=typeof b)return!1;for(var d in a)if(!1===b.apply(c,[d,a[d]]))return!1;return!0};z._traceProto=c;z._uniqPush=e;z._slice=function(a,b){return Array.prototype.slice.call(a,b||0)};z._copy=function(a,b){for(var c in a)b[c]=a[c];return b};z._merge=function(a,b){for(var c in a)c in b||(b[c]=a[c]);return b};z._keys=function(a){var b,c=[];for(b in a)c.push(b);return c};z._containsAll=function(a,b){for(var c=0,d=0,e=b.length;d<e;d++)if(-1!=a.indexOf(b[d]))c++;else return!1;return 0<c};z._isPrivate=
function(a){return a.toString().match(/^_/)};z._array=function(a){return Array.prototype.slice.call(a,0)};z._isPlainObject=function(a){if("object"!=typeof a||!(a instanceof Object)||!Object.prototype.isPrototypeOf(a))return!1;var b=0;c(a,function(){if(1<++b)return!1});return 1<b?!1:!0};$global("$implement",function(a,b){var c=b.__implns__;c?z._uniqPush(c,a):b.__implns__=a instanceof Array?a.slice(0):[a];return b});$global("$extend",function(a,b){var c=a.prototype,d=function(){};d.prototype=b.prototype;
a.prototype=new d;d=a.prototype;c&&z._copy(c,d);d.constructor=a;a.baseProto=b.prototype});$global("$base",function(a,b,c){var c=c||arguments.callee.caller,d=null,e=null;e||(z._everyKey(a,function(b){if(a[b]==c)return e=b,d=a.constructor.baseProto,!1}),e||z._traceProto(a,function(a){z._everyKey(a,function(b){if(a.hasOwnProperty(b)&&a[b]==c)return d=a.constructor.baseProto,e=b,!1});a.constructor==c&&(e="constructor",d=a.constructor.baseProto);if(d)return!1}));if(e&&d){var f=d[e];if(f&&"function"==typeof f)return f.apply(a,
b)}});$global("$include",function(a,b,c){c=c||[];c=c.concat("onIncluded","__implns__");z._everyKey(a,function(a,d){-1==c.indexOf(a)&&(b[a]=d)});a.onIncluded&&a.onIncluded.call(b)});$global("$enum",function(a){if(1==arguments.length&&"object"==typeof a)return a;var b={};z._every(arguments,function(a){b[a]={}});return b});$global("$property",d);$global("$fn",b);$global("$clone",function(a){var c;c=a.constructor==Object?new a.constructor:new this.constructor(a.valueOf());for(var d in a)c[d]!=a[d]&&(c[d]=
"object"==typeof a[d]?b(a[d]):a[d]);c.toString=a.toString;c.valueOf=a.valueOf;return c});$global("$trace",f)});
$run(function(){function e(b,c){if(null!==b){var a=typeof b;"object"!=a&&"function"!=a&&(b=new (eval(a.charAt(0).toUpperCase()+a.slice(1)))(b));var d=(a=b instanceof e.Proxy)?b:new e.Proxy(b);a||z._everyKey(b,function(a,b){"function"==typeof b&&(d[a]=b.bind(d.target))});e.findWrapper(d.__target__,c).forEach(function(a){var b=["onIncluded","__implns__"];z._everyKey(a,function(c,e){if(-1==b.indexOf(c)){var f=d.__target__;"function"==typeof e?d[c]=function(){var b,c=[];z._everyKey(a,function(a,b){"function"==
typeof b&&"onIncluded"!==a&&!f.hasOwnProperty(a)&&(f[a]=b,c.push(a))});b=c;var d;try{d=e.apply(f,arguments)}finally{if(b.length)for(var i=0,g=b.length;i<g;i++)delete f[b[i]]}return d}:f[c]=e}});a.onIncluded&&a.onIncluded.call(d)});return d}}eval($global.all);e.Proxy=function(b){this.__target__=b};e.getWrapperNamesExcept=function(b,c){var c=c||f,a=this.__wrapper[b],d=[];if(a){var d=c,e=[],g;for(g in a)d!==g&&e.push(g);d=e}return d};var f="default";e.__wrapper={};e.regWrapper=function(b,c,a){a=a||f;
if(c instanceof Array)c.forEach(function(c){e.regWrapper(b,c,a)});else{var d=this.__wrapper[c];d||(d=this.__wrapper[c]={"default":null});if(this.__wrapper[c][a])throw"name '"+a+"' has been registered.";this.__wrapper[c][a]=b}};e.setDefault=function(b,c){var a=this.getWrapper(b,c);a&&(this.__wrapper[b][f]=a)};e.removeWrapper=function(b,c){b&&c&&(b instanceof Array?b.forEach(function(a){e.removeWrapper(a,c)}):(this.__wrapper[b][f]==this.getWrapper(b,c)&&this.setDefault(b,null),delete this.__wrapper[b][c]))};
e.getWrapper=function(b,c){var c=c||f,a=this.__wrapper[b];if(a)return a[c]};e.findWrapper=function(b,c){var a=typeof b,d=[];("object"===a||"function"===a)&&z._traceProto(b,function(a){var b=e.getWrapper(a.constructor,c);b&&z._uniqPush(d,b);if(a=a.__implns__)a=a.slice(0),a.forEach(function(a){(b=e.getWrapper(a,c))&&z._uniqPush(d,b)})});return d.reverse()};e.make=function(b){return{can:function(c,a){if("string"==typeof c)d(b,a,c);else if("object"==typeof c)for(var e in c)d(b,c[e],e);return this},lose:function(c){if("string"==
typeof c){var a=e.getWrapper(b,f);a&&delete a[c]}else if("object"==typeof c)for(a in c){var c=a,d=e.getWrapper(b,f);d&&delete d[c]}return this}}};var d=function(b,c,a){if(a=a||c.name){var d=e.getWrapper(b,f);d?d[a]=c:(d={},d[a]=c,e.regWrapper(d,b))}};e.createSandbox=function(b,c){return function(a){if(a){e.make(b).can(c);var d;try{d=a()}finally{e.make(b).lose(c)}return d}}};e.onceWrap=function(b,c,a){return e.makeSandbox(b,c)(a)};$global("$",e);$global("$$",function(b,c){if(null!==b){var a=typeof b;
"object"!=a&&"function"!=a&&(b=new (eval(a.charAt(0).toUpperCase()+a.slice(1)))(b));e.findWrapper(b,c).forEach(function(a){$include(a,b)});return b}})});$run(function(){eval($global.all);var e={onIncluded:"[function()]"};z.PObject={__implns__:Array};z.PModule=e;$global("$module",function(f){$implement(e,f);return f})});
$run(function(){eval($global.all);var e={target:"object",get:"function(name)",set:"function(member, value)",invoke:"function(funcName, args)",wrapWith:"function(wrapperName)",include:"function(module)",implement:"function(protocol)"},f=$module({onIncluded:function(){$implement(e,this)},get:function(d){return this[d]},set:function(d,b){this[d]=b;return this},invoke:function(d,b){return this[d].apply(this,b)},$:function(d){return $(this,d)},$$:function(d){$$(this,d);return this},implement:function(d){$implement(d,
this);return this},include:function(d){$include(d,this);return this}});$.regWrapper(f,Object);z.PMObject=e;z.MObject=f});
$run(function(){eval($global.all);var e={type:"function",member:{baseProto:{type:"object",required:!1},__implns__:{type:"Array",required:!1},__cls_implns__:{type:"Array",required:!1}}},f=$module({onIncluded:function(){this.__cls_implns__=[];$implement(e,this)},extend:function(d){$extend(this,d);delete this.extend;return this},classImplement:function(d){this.__cls_implns__||(this.__cls_implns__=[]);z._uniqPush(this.__cls_implns__,d);return this},getClassImplns:function(){return this.__cls_implns__}});
$.regWrapper(f,Function,"MClass");z.PClass=e;z.MClass=f;$global("$class",function(d){return $$(d,"MClass")})});
$run(function(){function e(){this.__implns__=[]}eval($global.all);var f={get:"function(name)",set:"function(name, value)",proto:"function",base:"function()",include:"function(module)",property:"function()",implement:"function(protocol)",getOwnImplns:"function()",getImplns:"function()"};e.prototype=$implement(f,{property:function(){$property.apply(this,[this].concat(z._slice(arguments)));return this},include:function(d){$include(d,this);return this},get:function(d){return this[d]},set:function(d,b){this[d]=
b},proto:void 0!={}.__proto__?function(){return this.__proto__}:function(){return this.constructor.prototype===this?this.constructor.baseProto:this.constructor.prototype},base:function(){return $base(this,arguments,arguments.callee.caller)},implement:function(d){$implement(d,this)},getOwnImplns:function(){return this.hasOwnProperty("__implns__")?this.__implns__.slice(0):[]},getImplns:function(){var d=this.getOwnImplns(),b=this.constructor.getClassImplns&&this.constructor.getClassImplns();b||(b=this.constructor.__class_implns__);
b&&z._uniqPush(d,b);z._traceProto(this,function(b){b.hasOwnProperty("__implns__")&&(b=b.__implns__)&&(d=d.concat(b))});return d}});e.prototype.constructor=e;e.baseProto=Object.prototype;$class(e);z.PBase=f;z.Base=e});
$run(function(){function e(d){var b={},c=typeof d;if("object"==c)return d;switch(c){case "string":b.typeOf=d;break;case "function":b.instanceOf=d;break;case "undefined":b.typeOf=c}$implement(f,b);return b}eval($global.all);var f={typeOf:"[string]",instanceOf:"[object]",prototypeOf:"[object]"};z.PTypeSpec=f;z.parseTypeSpec=e;$global("$is",function(d,b){if(null===d)return d===b;var d=e(d),c=d.typeOf;if(c&&(-1!=c.indexOf("function")&&(c="function"),typeof b!==c)||d.instanceOf&&!(b instanceof d.instanceOf))return!1;
if(c=d.prototypeOf)if(c instanceof Array){if(!z._every(c,function(a){return a.isPrototypeOf(b)}))return!1}else if(!c.isPrototypeOf(b))return!1;return!0})});
$run(function(){function e(d){var b=arguments.callee;if(d instanceof b)return d;var c=typeof d;"string"==c?z._copy(b.__parse(d),this):"object"==c?z._copy(d,this):"function"==c&&(this.type=d);z._merge(arguments.callee.option,this)}eval($global.all);var f={required:"boolean",type:[Object,Array],ownProperty:"boolean",check:"function(o, name)",value:Object};e.option={required:!0,type:null,ownProperty:!1};e.__parse=function(d){var b={},c=d.match(/^\[(.*)\]$/);c&&(b.required=!1,d=c[1]);b.type=-1!=d.indexOf("|")?
d.split("|"):d;return b};e.prototype=$implement(f,{check:function(d,b){var c=d[b];if(null===c||void 0===c)return!this.required;if(this.type){var a=this.type;if($is(Array,a)){for(var e=!1,f=0,g=a.length;f<g;f++)if($is(a[f],c)){e=!0;break}if(!e)return!1}else if(!$is(a,c))return!1}return this.ownProperty&&!d.hasOwnProperty(b)?!1:!0}});$class(e).extend(z.Base);z.MemberSpec=e});
$run(function(){function e(b,c){var a={base:null,freeze:!1};a.type=c||Object;a.member=b;b.member&&(z._copy(b,a),a.type=b.type||Object);a.type&&(a.type=z.parseTypeSpec(a.type));var e=z.MemberSpec,f,g=a.member;for(f in g){var h=g[f];h instanceof e||(g[f]=new e(h))}$implement(d,a);return a}function f(b,c){if(!b.__implns__||-1==b.__implns__.indexOf(d))b=e(b);if(b.base&&!f(b.base,c)||b.type&&!$is(b.type,c))return!1;if(b.member){var a,i=b.member;for(a in i)if(!i[a].check(c,a))return!1;if(b.freeze){var m=
{};$trace(b,"base",function(a){z._merge(a.member,m)});for(a in c)if(!(a in m))return!1}}return!0}eval($global.all);var d=e({member:{base:"[object]",member:"[object]",type:z.PTypeSpec,freeze:"[boolean]"}});z.PProtocol=d;$global("$protocol",e);$global("$support",f)});
$run(function(){eval($global.all);$global("$option",function(){var e=arguments,f=arguments.callee.caller,d=e[0]||f.arguments[0]||{},e=e[1]||f.option,b,c;for(b in e)f=e[b],c=typeof f,"object"==c?f.hasOwnProperty.required||(f.required=!1):"object"==c&&(e[b]={type:c,required:!1});b=$protocol(e);if($support(b,d)){b=b.member;for(var a in b)a in d||(d[a]=b[a].value);return d}throw"arguments invalid";})});
$run(function(){function e(d,b){var b=b||{},c=[],a,e,f,g;f=0;for(g=d.length;f<g;f++)a=d[f],e=typeof a,"function"==e?a.option?c.push({params:[Object],fn:a,useOption:!0}):c.push({params:[],fn:a,useOption:!1}):$is(Array,a)&&(e=a[1],$is(Array,e)?c.push({params:e,fn:a[0],useOption:!1}):z._isPlainObject(e)&&(a[0].option=a[1],c.push({params:[Object],fn:a[0],useOption:!0})));f=0;for(g=c.length;f<g;f++)a=c[f],e=a.params.length,b[e]||(b[e]=[]),b[e].push(a);return b}function f(d,b){var c=typeof b,a=typeof d;
if("string"!==a||"object"===d)if("object"===c||"function"===c){if($is(d,b))return!0}else{if({string:String,number:Number,"boolean":Boolean}[c]===d)return!0}else if(c==a)return!0;return!1}eval($global.all);$global("$overload",function(){var d=function(){var b=arguments,c;a:{c=b;if(b=b.callee.fnMap[c.length]){var a=c[0],d=1==c.length&&"object"===typeof a,e=0,g,h,n,k,j,e=0;for(g=b.length;e<g;e++)if(h=b[e],k=h.fn,j=h.params,h.useOption){if(d&&z._isPlainObject(a)&&(j=k.option,z._keys(j).length>=z._keys(a).length&&
$support(j,a))){c=k;break a}}else{var l=!0;h=0;for(n=j.length;h<n&&!(l=f(j[h],c[h]),!l);h++);if(l){c=k;break a}}}c=void 0}if(c)return c.apply(this,arguments)};d.fnMap=e(arguments);d.overload=function(b,c){if(b){var a=[];b&&c?a.push([b,c]):a.push(b);e(a,this.fnMap)}};return d})});
$run(function(){eval($global.all);var e={addListener:"function(event, listener)",on:"function(event, listener)",removeListener:"function(event, listener)",un:"function(event, listener)",getListerners:"function(event)",fire:"function(event, args)"},f=$module({onIncluded:function(){this.__listeners={};$implement(e,this)},addListener:function(d,b){var c=this.__listeners[d];c||(c=this.__listeners[d]=[]);c.push(b);return this},removeListener:function(d,b){var c=this.__listeners[d];if(c)return this.__listeners[d]=
c.filter(function(a){return a!=b}),this},getListerners:function(d){return this.__listeners[d]},fire:function(d,b){this.getListerners(d).forEach(function(c){c(b)});return this}});$.regWrapper(f,Object,"MEvent");z.MEvent=f});
$run(function(){eval($global.all);var e=$module({methods:function(){var e=this;return this.allKeys().filter(function(d){return"function"==typeof e[d]})},publicMethods:function(){return this.methods().filter(function(e){return!z._isPrivate(e)})},privateMethods:function(){return this.methods().filter(function(e){return z._isPrivate(e)})},fields:function(){var e=this;return this.allKeys().filter(function(d){return"function"!=typeof e[d]})},publicFields:function(){return this.fields().filter(function(e){return!z._isPrivate(e)})},
privateFields:function(){return this.fields().filter(function(e){return z._isPrivate(e)})},keys:function(){return Object.keys(this)},allKeys:function(){return z._keys(this)},type:function(){return typeof this},protoLink:function(){var e=[];z._traceProto(this,function(d){e.push(d)});return e},proto:function(){return void 0!=={}.__proto__?this.__proto__:this.constructor.prototype},creator:function(){return this.constructor},implns:function(){var e=this.__implementions__;return e?[]:e.slice(0)}});z.MInspect=
e;$.regWrapper(e,Object,"MInspect");$global("$inspect",function(e){return $(e).$("MInspect")})});
