(function(e){function f(){this.__member={}}function d(b,a){var c=arguments.callee,d=typeof b;if("object"==d)for(var e in b)c.set(e,b[e]);else"string"==d&&c.set(b,a);return c}f.prototype={set:function(b,a){this.get(b)&&this.destroy(b);this.__member[b]=a;this.__onChange();return this},__onChange:function(){this.all=this.__getEvalCode()},get:function(b){return this.__member[b]},list:function(){var b=[],a;for(a in this.__member)b.push(a);return b},destroy:function(b){b in this.__member&&(delete this.__member[b],
this.__onChange())},exportTo:function(b,a){"string"==typeof b&&(b=[b]);var c=this;(b||this.list()).forEach(function(b){a[b]=c.get(b)})},run:function(b){var a=b.__args;a||(a=(a=b.toString().match(/\((.*)?\)/))&&a[1]?a[1].replace(/ /g,"").split(","):[],b.__args=a);0===a.length&&(a=this.list(),b=b.toString(),b=b.substr(b.indexOf("{")),b=eval("(function(){ return function("+a.join(",")+")"+b+"})()"));for(var c=[],d=0,e=a.length;d<e;d++)c.push(this.get(a[d]));b.apply({},c);return this},__getEvalCode:function(){var b=
[];this.list().forEach(function(a){b.push(a+"=$global.get('"+a+"')")});return"var "+b.join(",")+";"}};var a=new f,c;for(c in a)d[c]=a[c];a={};a.VariableManager=f;d("z",a);e.$global=d;e.$run=function(b){var a={};b.apply(a,arguments);return a}})(this);
$run(function(){eval($global.all);var e=function(){};e.info=function(){};e.warn=function(){};e.debug=function(){};e.error=function(){};if("undefined"!=typeof console){"function"==typeof console.log&&(e=function(a){console.log(a)});for(var f=["info","warn","error","debug"],d=f.length;d--;){var a=f[d-1];"function"==typeof console[a]&&(e[a]=function(a){return function(b){console[a](b)}}(a))}}$global("$log",e)});
$run(function(){function e(b,a){if(a instanceof Array)for(var c=0,d=a.length;c<d;c++)e(b,a[c]);else if(b.indexOf)-1==b.indexOf(a)&&b.push(a);else{for(c=b.length;c--;)if(b[c]==a)return;b.push(a)}}function f(b,a,c,d){for(;b;){if(!1===c.apply(d,[b]))return!1;b=b[a]}return!0}function d(){var b=arguments,a=b[0],c=typeof b[1];"string"==c?(c=b[1],b=b[2]||{},!b.hasOwnProperty("writable")&&(!b.set&&!b.get)&&(b.writable=!0),Object.defineProperty(a,c,b)):"object"==c&&z._everyKey(b[1],function(b,c){d(a,b,c)})}
function a(){return a.caller.apply(this,arguments)}eval($global.all);var c=void 0!=={}.__proto__?function(b,a,c){return f(b.__proto__,"__proto__",a,c)}:function(b,a,c){var d=b.constructor.prototype;d==b&&(d=b.constructor.baseProto);for(;d;){if(!1===a.apply(c,[d]))return!1;d=d.constructor.baseProto}if(b.constructor!==Object&&!1===a.apply(c,[Object.prototype]))return!1};z._every=function(b,a,c){if(!b)return!0;for(var d=0,e=b.length;d<e;d++)if(!1===a.apply(c,[b[d]]))return!1;return!0};z._everyKey=function(b,
a,c){if("function"!=typeof a)return!1;for(var d in b)if(!1===a.apply(c,[d,b[d]]))return!1;return!0};z._traceProto=c;z._uniqPush=e;z._slice=function(b,a){return Array.prototype.slice.call(b,a||0)};z._copy=function(b,a){for(var c in b)a[c]=b[c];return a};z._merge=function(b,a){for(var c in b)c in a||(a[c]=b[c]);return a};z._keys=function(b){var a,c=[];for(a in b)c.push(a);return c};z._containsAll=function(b,a){for(var c=0,d=0,e=a.length;d<e;d++)if(-1!=b.indexOf(a[d]))c++;else return!1;return 0<c};z._isPrivate=
function(b){return b.toString().match(/^_/)};z._array=function(b){return Array.prototype.slice.call(b,0)};z._isPlainObject=function(b){if("object"!=typeof b||!(b instanceof Object)||!Object.prototype.isPrototypeOf(b))return!1;var a=0;c(b,function(){if(1<++a)return!1});return 1<a?!1:!0};$global("$implement",function(b,a){var c=a.__implns__;c?z._uniqPush(c,b):a.__implns__=b instanceof Array?b.slice(0):[b];return a});$global("$extend",function(b,a){var c=b.prototype,d=function(){};d.prototype=a.prototype;
b.prototype=new d;d=b.prototype;c&&z._copy(c,d);d.constructor=b;b.baseProto=a.prototype});$global("$base",function(b,a,c){var c=c||arguments.callee.caller,d=null,e=null;e||(z._everyKey(b,function(a){if(b[a]==c)return e=a,d=b.constructor.baseProto,!1}),e||z._traceProto(b,function(a){z._everyKey(a,function(b){if(a.hasOwnProperty(b)&&a[b]==c)return d=a.constructor.baseProto,e=b,!1});a.constructor==c&&(e="constructor",d=a.constructor.baseProto);if(d)return!1}));if(e&&d){var f=d[e];if(f&&"function"==typeof f)return f.apply(b,
a)}});$global("$include",function(a,c,d){d=d||[];d=d.concat("onIncluded","__implns__");z._everyKey(a,function(a,b){-1==d.indexOf(a)&&(c[a]=b)});a.onIncluded&&a.onIncluded.call(c)});$global("$enum",function(a){if(1==arguments.length&&"object"==typeof a)return a;var c={};z._every(arguments,function(a){c[a]={}});return c});$global("$property",d);$global("$fn",a);$global("$clone",function(b){var c;c=b.constructor==Object?new b.constructor:new this.constructor(b.valueOf());for(var d in b)c[d]!=b[d]&&(c[d]=
"object"==typeof b[d]?a(b[d]):b[d]);c.toString=b.toString;c.valueOf=b.valueOf;return c});$global("$trace",f)});
$run(function(){function e(a,c){if(null!==a){var b=typeof a;"object"!=b&&"function"!=b&&(a=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));var d=(b=a instanceof e.Proxy)?a:new e.Proxy(a);b||z._everyKey(a,function(a,b){"function"==typeof b&&(d[a]=b.bind(d.target))});e.findWrapper(d.target,c).forEach(function(a){$include(a,d)});return d}}eval($global.all);e.Proxy=function(a){this.target=a};e.getWrapperNamesExcept=function(a,c){var c=c||f,b=this.__wrapper[a],d=[];if(b){var d=c,e=[],g;for(g in b)d!==
g&&e.push(g);d=e}return d};var f="default";e.__wrapper={};e.regWrapper=function(a,c,b){b=b||f;if(c instanceof Array)c.forEach(function(c){e.regWrapper(a,c,b)});else{var d=this.__wrapper[c];d||(d=this.__wrapper[c]={"default":null});if(this.__wrapper[c][b])throw"name '"+b+"' has been registered.";this.__wrapper[c][b]=a}};e.setDefault=function(a,c){var b=this.getWrapper(a,c);b&&(this.__wrapper[a][f]=b)};e.removeWrapper=function(a,c){a&&c&&(a instanceof Array?a.forEach(function(a){e.removeWrapper(a,c)}):
(this.__wrapper[a][f]==this.getWrapper(a,c)&&this.setDefault(a,null),delete this.__wrapper[a][c]))};e.getWrapper=function(a,c){var c=c||f,b=this.__wrapper[a];if(b)return b[c]};e.findWrapper=function(a,c){var b=typeof a,d=[];("object"===b||"function"===b)&&z._traceProto(a,function(a){var b=e.getWrapper(a.constructor,c);b&&z._uniqPush(d,b);if(a=a.__implns__)a=a.slice(0),a.forEach(function(a){(b=e.getWrapper(a,c))&&z._uniqPush(d,b)})});return d.reverse()};e.make=function(a){return{can:function(c,b){if("string"==
typeof c)d(a,b,c);else if("object"==typeof c)for(var e in c)d(a,c[e],e);return this},lose:function(c){if("string"==typeof c){var b=e.getWrapper(a,f);b&&delete b[c]}else if("object"==typeof c)for(b in c){var c=b,d=e.getWrapper(a,f);d&&delete d[c]}return this}}};var d=function(a,c,b){if(b=b||c.name){var d=e.getWrapper(a,f);d?d[b]=c:(d={},d[b]=c,e.regWrapper(d,a))}};e.createSandbox=function(a,c){return function(b){if(b){e.make(a).can(c);var d;try{d=b()}finally{e.make(a).lose(c)}return d}}};e.onceWrap=
function(a,c,b){return e.makeSandbox(a,c)(b)};$global("$",e);$global("$$",function(a,c){if(null!==a){var b=typeof a;"object"!=b&&"function"!=b&&(a=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));a instanceof e.Proxy||(a.target&&(a.originTarget=a.target),a.target=a);e.findWrapper(a.target,c).forEach(function(b){$include(b,a)});return a}})});
$run(function(){eval($global.all);var e={onIncluded:"[function()]"};z.PObject={__implns__:Array};z.PModule=e;$global("$module",function(f){$implement(e,f);return f})});
$run(function(){eval($global.all);var e={target:"object",get:"function(name)",set:"function(member, value)",invoke:"function(funcName, args)",wrapWith:"function(wrapperName)",include:"function(module)",implement:"function(protocol)"},f=$module({onIncluded:function(){$implement(e,this)},get:function(d){return this.target[d]},set:function(d,a){this.target[d]=a;return this},invoke:function(d,a){return this.target[d].apply(this.target,a)},wrapWith:function(d){$$(this,d);return this},implement:function(d){$implement(d,
this.target);return this},include:function(d){$include(d,this.target);return this}});$.regWrapper(f,Object);z.PMObject=e;z.MObject=f});
$run(function(){eval($global.all);var e={type:"function",member:{baseProto:{type:"object",required:!1},__implns__:{type:"Array",required:!1},__cls_implns__:{type:"Array",required:!1}}},f=$module({onIncluded:function(){this.__cls_implns__=[];this.implement(e)},extend:function(d){$extend(this.target,d);delete this.extend;return this},classImplement:function(d){this.target.__cls_implns__||(this.target.__cls_implns__=[]);z._uniqPush(this.target.__cls_implns__,d);return this.target},getClassImplns:function(){return this.target.__cls_implns__}});
$.regWrapper(f,Function,"MClass");z.PClass=e;z.MClass=f;$global("$class",function(d){return $(d).wrapWith("MClass")})});
$run(function(){function e(){this.__implns__=[]}eval($global.all);var f={get:"function(name)",set:"function(name, value)",proto:"function",base:"function()",include:"function(module)",property:"function()",implement:"function(protocol)",getOwnImplns:"function()",getImplns:"function()"};e.prototype=$implement(f,{property:function(){$property.apply(this,[this].concat(z._slice(arguments)));return this},include:function(d){$include(d,this);return this},get:function(d){return this[d]},set:function(d,a){this[d]=
a},proto:void 0!={}.__proto__?function(){return this.__proto__}:function(){return this.constructor.prototype===this?this.constructor.baseProto:this.constructor.prototype},base:function(){return $base(this,arguments,arguments.callee.caller)},implement:function(d){$implement(d,this)},getOwnImplns:function(){return this.hasOwnProperty("__implns__")?this.__implns__.slice(0):[]},getImplns:function(){var d=this.getOwnImplns(),a=this.constructor.getClassImplns&&this.constructor.getClassImplns();a||(a=this.constructor.__class_implns__);
a&&z._uniqPush(d,a);z._traceProto(this,function(a){a.hasOwnProperty("__implns__")&&(a=a.__implns__)&&(d=d.concat(a))});return d}});e.prototype.constructor=e;e.baseProto=Object.prototype;$class(e);z.PBase=f;z.Base=e});
$run(function(){function e(d){var a={},c=typeof d;if("object"==c)return d;switch(c){case "string":a.typeOf=d;break;case "function":a.instanceOf=d;break;case "undefined":a.typeOf=c}$implement(f,a);return a}eval($global.all);var f={typeOf:"[string]",instanceOf:"[object]",prototypeOf:"[object]"};z.PTypeSpec=f;z.parseTypeSpec=e;$global("$is",function(d,a){if(null===d)return d===a;var d=e(d),c=d.typeOf;if(c&&(-1!=c.indexOf("function")&&(c="function"),typeof a!==c)||d.instanceOf&&!(a instanceof d.instanceOf))return!1;
if(c=d.prototypeOf)if(c instanceof Array){if(!z._every(c,function(b){return b.isPrototypeOf(a)}))return!1}else if(!c.isPrototypeOf(a))return!1;return!0})});
$run(function(){function e(d){var a=arguments.callee;if(d instanceof a)return d;var c=typeof d;"string"==c?z._copy(a.__parse(d),this):"object"==c?z._copy(d,this):"function"==c&&(this.type=d);z._merge(arguments.callee.option,this)}eval($global.all);var f={required:"boolean",type:[Object,Array],ownProperty:"boolean",check:"function(o, name)",value:Object};e.option={required:!0,type:null,ownProperty:!1};e.__parse=function(d){var a={},c=d.match(/^\[(.*)\]$/);c&&(a.required=!1,d=c[1]);a.type=-1!=d.indexOf("|")?
d.split("|"):d;return a};e.prototype=$implement(f,{check:function(d,a){var c=d[a];if(null===c||void 0===c)return!this.required;if(this.type){var b=this.type;if($is(Array,b)){for(var e=!1,f=0,g=b.length;f<g;f++)if($is(b[f],c)){e=!0;break}if(!e)return!1}else if(!$is(b,c))return!1}return this.ownProperty&&!d.hasOwnProperty(a)?!1:!0}});$class(e).extend(z.Base);z.MemberSpec=e});
$run(function(){function e(a,c){var b={base:null,freeze:!1};b.type=c||Object;b.member=a;a.member&&(z._copy(a,b),b.type=a.type||Object);b.type&&(b.type=z.parseTypeSpec(b.type));var e=z.MemberSpec,f,g=b.member;for(f in g){var h=g[f];h instanceof e||(g[f]=new e(h))}$implement(d,b);return b}function f(a,c){if(!a.__implns__||-1==a.__implns__.indexOf(d))a=e(a);if(a.base&&!f(a.base,c)||a.type&&!$is(a.type,c))return!1;if(a.member){var b,l=a.member;for(b in l)if(!l[b].check(c,b))return!1;if(a.freeze){var m=
{};$trace(a,"base",function(a){z._merge(a.member,m)});for(b in c)if(!(b in m))return!1}}return!0}eval($global.all);var d=e({member:{base:"[object]",member:"[object]",type:z.PTypeSpec,freeze:"[boolean]"}});z.PProtocol=d;$global("$protocol",e);$global("$support",f)});
$run(function(){eval($global.all);$global("$option",function(){var e=arguments,f=arguments.callee.caller,d=e[0]||f.arguments[0]||{},e=e[1]||f.option,a,c;for(a in e)f=e[a],c=typeof f,"object"==c?f.hasOwnProperty.required||(f.required=!1):"object"==c&&(e[a]={type:c,required:!1});a=$protocol(e);if($support(a,d)){a=a.member;for(var b in a)b in d||(d[b]=a[b].value);return d}throw"arguments invalid";})});
$run(function(){function e(d,a){var a=a||{},c=[],b,e,f,g;f=0;for(g=d.length;f<g;f++)b=d[f],e=typeof b,"function"==e?b.option?c.push({params:[Object],fn:b,useOption:!0}):c.push({params:[],fn:b,useOption:!1}):$is(Array,b)&&(e=b[1],$is(Array,e)?c.push({params:e,fn:b[0],useOption:!1}):z._isPlainObject(e)&&(b[0].option=b[1],c.push({params:[Object],fn:b[0],useOption:!0})));f=0;for(g=c.length;f<g;f++)b=c[f],e=b.params.length,a[e]||(a[e]=[]),a[e].push(b);return a}function f(d,a){var c=typeof a,b=typeof d;
if("string"!==b||"object"===d)if("object"===c||"function"===c){if($is(d,a))return!0}else{if({string:String,number:Number,"boolean":Boolean}[c]===d)return!0}else if(c==b)return!0;return!1}eval($global.all);$global("$overload",function(){var d=function(){var a=arguments,c;a:{c=a;if(a=a.callee.fnMap[c.length]){var b=c[0],d=1==c.length&&"object"===typeof b,e=0,g,h,n,j,i,e=0;for(g=a.length;e<g;e++)if(h=a[e],j=h.fn,i=h.params,h.useOption){if(d&&z._isPlainObject(b)&&(i=j.option,z._keys(i).length>=z._keys(b).length&&
$support(i,b))){c=j;break a}}else{var k=!0;h=0;for(n=i.length;h<n&&!(k=f(i[h],c[h]),!k);h++);if(k){c=j;break a}}}c=void 0}if(c)return c.apply(this,arguments)};d.fnMap=e(arguments);d.overload=function(a,c){if(a){var b=[];a&&c?b.push([a,c]):b.push(a);e(b,this.fnMap)}};return d})});
$run(function(){eval($global.all);var e={addListener:"function(event, listener)",on:"function(event, listener)",removeListener:"function(event, listener)",un:"function(event, listener)",getListerners:"function(event)",fire:"function(event, args)"},f=$module({onIncluded:function(){this.__listeners={};$implement(e,this)},on:this.addListener,addListener:function(d,a){var c=this.__listeners[d];c||(c=this.__listeners[d]=[]);c.push(a);return this},un:this.removeListener,removeListener:function(d,a){var c=
this.__listeners[d];if(c)return this.__listeners[d]=c.filter(function(b){return b!=a}),this},getListerners:function(d){return this.__listeners[d]},fire:function(d,a){this.getListerners(d).forEach(function(c){c(a)});return this}});z.MEvent=f});
$run(function(){eval($global.all);var e=$module({methods:function(){var e=this.allKeys(),d=this.target;return e.filter(function(a){return"function"==typeof d[a]})},publicMethods:function(){return this.methods().filter(function(e){return!z._isPrivate(e)})},privateMethods:function(){return this.methods().filter(function(e){return z._isPrivate(e)})},fields:function(){var e=this.allKeys(),d=this.target;return e.filter(function(a){return"function"!=typeof d[a]})},publicFields:function(){return this.fields().filter(function(e){return!z._isPrivate(e)})},
privateFields:function(){return this.fields().filter(function(e){return z._isPrivate(e)})},keys:function(){return Object.keys(this.target)},allKeys:function(){return z._keys(this.target)},type:function(){return typeof this.target},protoLink:function(){var e=[];z._traceProto(this.target,function(d){e.push(d)});return e},proto:function(){var e=this.target;return void 0!=={}.__proto__?e.__proto__:e.constructor.prototype},creator:function(){return this.target.constructor},implns:function(){var e=this.__implementions__;
return e?[]:e.slice(0)}});z.MInspect=e;$.regWrapper(e,Object,"MInspect");$global("$inspect",function(e){return $(e).wrapWith("MInspect")})});
