(function(d){function e(){this.__member={}}function c(a,b){var c=arguments.callee,d=typeof a;if("object"==d)for(var e in a)c.set(e,a[e]);else"string"==d&&c.set(a,b);return c}e.prototype={set:function(a,b){this.get(a)&&this.destroy(a);this.__member[a]=b;this.__onChange();return this},__onChange:function(){this.all=this.__getEvalCode()},get:function(a){return this.__member[a]},list:function(){var a=[],b;for(b in this.__member)a.push(b);return a},destroy:function(a){a in this.__member&&(delete this.__member[a],
this.__onChange())},exportTo:function(a,b){"string"==typeof a&&(a=[a]);var c=this;(a||this.list()).forEach(function(a){b[a]=c.get(a)})},run:function(a){var b=a.__args;b||(b=(b=a.toString().match(/\((.*)?\)/))&&b[1]?b[1].replace(/ /g,"").split(","):[],a.__args=b);0===b.length&&(b=this.list(),a=a.toString(),a=a.substr(a.indexOf("{")),a=eval("(function(){ return function("+b.join(",")+")"+a+"})()"));for(var c=[],d=0,e=b.length;d<e;d++)c.push(this.get(b[d]));a.apply({},c);return this},__getEvalCode:function(){var a=
[];this.list().forEach(function(b){a.push(b+"=$global.get('"+b+"')")});return"var "+a.join(",")+";"}};var b=new e,a;for(a in b)c[a]=b[a];b={};b.VariableManager=e;c("z",b);d.$global=c;d.$run=function(a){var b={};a.apply(b,arguments);return b}})(this);
$run(function(){eval($global.all);var d=function(){};d.info=function(){};d.warn=function(){};d.debug=function(){};d.error=function(){};if("undefined"!=typeof console){"function"==typeof console.log&&(d=function(a){console.log(a)});for(var e=["info","warn","error","debug"],c=e.length;c--;){var b=e[c-1];"function"==typeof console[b]&&(d[b]=function(a){return function(b){console[a](b)}}(b))}}$global("$log",d)});
$run(function(){function d(a,b){if(b instanceof Array)for(var c=0,f=b.length;c<f;c++)d(a,b[c]);else if(a.indexOf)-1==a.indexOf(b)&&a.push(b);else{for(c=a.length;c--;)if(a[c]==b)return;a.push(b)}}function e(){var a=arguments,b=a[0],c=typeof a[1];"string"==c?(c=a[1],a=a[2]||{},!a.hasOwnProperty("writable")&&(!a.set&&!a.get)&&(a.writable=!0),Object.defineProperty(b,c,a)):"object"==c&&z._everyKey(a[1],function(a,c){e(b,a,c)})}function c(){return c.caller.apply(this,arguments)}eval($global.all);var b=
void 0!=={}.__proto__?function(a,b,c){return _trace(a.__proto__,"__proto__",b,c)}:function(a,b,c){var d=a.constructor.prototype;d==a&&(d=a.constructor.baseProto);for(;d;){if(!1===b.apply(c,[d]))return!1;d=d.constructor.baseProto}if(a.constructor!==Object&&!1===b.apply(c,[Object.prototype]))return!1};z._every=function(a,b,c){if(!a)return!0;for(var d=0,e=a.length;d<e;d++)if(!1===b.apply(c,[a[d]]))return!1;return!0};z._everyKey=function(a,b,c){if("function"!=typeof b)return!1;for(var d in a)if(!1===
b.apply(c,[d,a[d]]))return!1;return!0};z._traceProto=b;z._uniqPush=d;z._slice=function(a,b){return Array.prototype.slice.call(a,b||0)};z._copy=function(a,b){for(var c in a)b[c]=a[c];return b};z._merge=function(a,b){for(var c in a)c in b||(b[c]=a[c]);return b};z._keys=function(a){var b,c=[];for(b in a)c.push(b);return c};z._containsAll=function(a,b){for(var c=0,d=0,e=b.length;d<e;d++)if(-1!=a.indexOf(b[d]))c++;else return!1;return 0<c};z._isPrivate=function(a){return a.toString().match(/^_/)};z._array=
function(a){return Array.prototype.slice.call(a,0)};z._isPlainObject=function(a){if("object"!=typeof a||!(a instanceof Object)||!Object.prototype.isPrototypeOf(a))return!1;var c=0;b(a,function(){if(1<++c)return!1});return 1<c?!1:!0};$global("$implement",function(a,b){var c=b.__implns__;c?z._uniqPush(c,a):b.__implns__=a instanceof Array?a.slice(0):[a];return b});$global("$extend",function(a,b){var c=a.prototype,d=function(){};d.prototype=b.prototype;a.prototype=new d;d=a.prototype;c&&z._copy(c,d);
d.constructor=a;a.baseProto=b.prototype});$global("$base",function(a,b,c){var c=c||arguments.callee.caller,d=null,e=null;e||(z._everyKey(a,function(b){if(a[b]==c)return e=b,d=a.constructor.baseProto,!1}),e||z._traceProto(a,function(a){z._everyKey(a,function(b){if(a.hasOwnProperty(b)&&a[b]==c)return d=a.constructor.baseProto,e=b,!1});a.constructor==c&&(e="constructor",d=a.constructor.baseProto);if(d)return!1}));if(e&&d){var h=d[e];if(h&&"function"==typeof h)return h.apply(a,b)}});$global("$include",
function(a,b,c){c=c||[];c=c.concat("onIncluded","__implns__");z._everyKey(a,function(a,d){-1==c.indexOf(a)&&(b[a]=d)});a.onIncluded&&a.onIncluded.call(b)});$global("$enum",function(a){if(1==arguments.length&&"object"==typeof a)return a;var b={};z._every(arguments,function(a){b[a]={}});return b});$global("$property",e);$global("$fn",c);$global("$clone",function(a){var b;b=a.constructor==Object?new a.constructor:new this.constructor(a.valueOf());for(var d in a)b[d]!=a[d]&&(b[d]="object"==typeof a[d]?
c(a[d]):a[d]);b.toString=a.toString;b.valueOf=a.valueOf;return b});$global("$trace",function(a,b,c,d){for(;a;){if(!1===c.apply(d,[a]))return!1;a=a[b]}return!0})});
$run(function(){function d(b,a){if(null!==b){var c=typeof b;"object"!=c&&"function"!=c&&(b=new (eval(c.charAt(0).toUpperCase()+c.slice(1)))(b));var e=(c=b instanceof d.Proxy)?b:new d.Proxy(b);c||z._everyKey(b,function(a,b){"function"==typeof b&&(e[a]=b.bind(e.target))});d.findWrapper(e.target,a).forEach(function(a){$include(a,e)});return e}}eval($global.all);d.Proxy=function(b){this.target=b};d.getWrapperNamesExcept=function(b,a){var a=a||e,c=this.__wrapper[b],d=[];if(c){var d=a,f=[],g;for(g in c)d!==
g&&f.push(g);d=f}return d};var e="default";d.__wrapper={};d.regWrapper=function(b,a,c){c=c||e;if(a instanceof Array)a.forEach(function(a){d.regWrapper(b,a,c)});else{var i=this.__wrapper[a];i||(i=this.__wrapper[a]={"default":null});if(this.__wrapper[a][c])throw"name '"+c+"' has been registered.";this.__wrapper[a][c]=b}};d.setDefault=function(b,a){var c=this.getWrapper(b,a);c&&(this.__wrapper[b][e]=c)};d.removeWrapper=function(b,a){b&&a&&(b instanceof Array?b.forEach(function(b){d.removeWrapper(b,a)}):
(this.__wrapper[b][e]==this.getWrapper(b,a)&&this.setDefault(b,null),delete this.__wrapper[b][a]))};d.getWrapper=function(b,a){var a=a||e,c=this.__wrapper[b];if(c)return c[a]};d.findWrapper=function(b,a){var c=typeof b,e=[];("object"===c||"function"===c)&&z._traceProto(b,function(b){var c=d.getWrapper(b.constructor,a);c&&z._uniqPush(e,c);if(b=b.__implns__)b=b.slice(0),b.forEach(function(b){(c=d.getWrapper(b,a))&&z._uniqPush(e,c)})});return e.reverse()};d.make=function(b){return{can:function(a,d){if("string"==
typeof a)c(b,d,a);else if("object"==typeof a)for(var e in a)c(b,a[e],e);return this},lose:function(a){if("string"==typeof a){var c=d.getWrapper(b,e);c&&delete c[a]}else if("object"==typeof a)for(c in a){var a=c,i=d.getWrapper(b,e);i&&delete i[a]}return this}}};var c=function(b,a,c){if(c=c||a.name){var i=d.getWrapper(b,e);i?i[c]=a:(i={},i[c]=a,d.regWrapper(i,b))}};d.createSandbox=function(b,a){return function(c){if(c){d.make(b).can(a);var e;try{e=c()}finally{d.make(b).lose(a)}return e}}};d.onceWrap=
function(b,a,c){return d.makeSandbox(b,a)(c)};$global("$",d);$global("$$",function(b,a){if(null!==b){var c=typeof b;"object"!=c&&"function"!=c&&(b=new (eval(c.charAt(0).toUpperCase()+c.slice(1)))(b));b instanceof d.Proxy||(b.target&&(b.originTarget=b.target),b.target=b);d.findWrapper(b.target,a).forEach(function(a){$include(a,b)});return b}})});
$run(function(){eval($global.all);var d={onIncluded:"[function()]"};z.IObject={__implns__:Array};z.IModule=d;$global("$module",function(e){$implement(d,e);return e})});
$run(function(){eval($global.all);var d={target:"object",get:"function(name)",set:"function(member, value)",invoke:"function(funcName, args)",wrapWith:"function(wrapperName)",include:"function(module)",implement:"function(protocol)"},e=$module({onIncluded:function(){$implement(d,this)},get:function(c){return this.target[c]},set:function(c,b){this.target[c]=b;return this},invoke:function(c,b){return this.target[c].apply(this.target,b)},wrapWith:function(c){$$(this,c);return this},implement:function(c){$implement(c,
this.target);return this},include:function(c){$include(c,this.target);return this}});$.regWrapper(e,Object);z.IMObject=d;z.MObject=e});
$run(function(){eval($global.all);var d={type:"function",member:{baseProto:{type:"object",required:!1},__implns__:{type:"Array",required:!1},__cls_implns__:{type:"Array",required:!1}}},e=$module({onIncluded:function(){this.__cls_implns__=[];this.implement(d)},extend:function(c){$extend(this.target,c);delete this.extend;return this},classImplement:function(c){this.target.__cls_implns__||(this.target.__cls_implns__=[]);z._uniqPush(this.target.__cls_implns__,c);return this.target},getClassImplns:function(){return this.target.__cls_implns__}});
$.regWrapper(e,Function,"MClass");z.IClass=d;z.MClass=e;$global("$class",function(c){return $(c).wrapWith("MClass")})});
$run(function(){function d(){this.__implns__=[]}eval($global.all);var e={get:"function(name)",set:"function(name, value)",proto:"function",base:"function()",include:"function(module)",property:"function()",implement:"function(protocol)",getOwnImplns:"function()",getImplns:"function()"};d.prototype=$implement(e,{property:function(){$property.apply(this,[this].concat(z._slice(arguments)));return this},include:function(c){$include(c,this);return this},get:function(c){return this[c]},set:function(c,b){this[c]=
b},proto:void 0!={}.__proto__?function(){return this.__proto__}:function(){return this.constructor.prototype===this?this.constructor.baseProto:this.constructor.prototype},base:function(){return $base(this,arguments,arguments.callee.caller)},implement:function(c){$implement(c,this)},getOwnImplns:function(){return this.hasOwnProperty("__implns__")?this.__implns__.slice(0):[]},getImplns:function(){var c=this.getOwnImplns(),b=this.constructor.getClassImplns&&this.constructor.getClassImplns();b||(b=this.constructor.__class_implns__);
b&&z._uniqPush(c,b);z._traceProto(this,function(a){a.hasOwnProperty("__implns__")&&(a=a.__implns__)&&(c=c.concat(a))});return c}});d.prototype.constructor=d;d.baseProto=Object.prototype;$class(d);z.IBase=e;z.Base=d});
$run(function(){function d(c){var b={},a=typeof c;if("object"==a)return c;switch(a){case "string":b.typeOf=c;break;case "function":b.instanceOf=c;break;case "undefined":b.typeOf=a}$implement(e,b);return b}eval($global.all);var e={typeOf:"[string]",instanceOf:"[object]",prototypeOf:"[object]"};z.ITypeSpec=e;z.parseTypeSpec=d;$global("$is",function(c,b){if(null===c)return c===b;var c=d(c),a=c.typeOf;if(a&&(-1!=a.indexOf("function")&&(a="function"),typeof b!==a)||c.instanceOf&&!(b instanceof c.instanceOf))return!1;
if(a=c.prototypeOf)if(a instanceof Array){if(!z._every(a,function(a){return a.isPrototypeOf(b)}))return!1}else if(!a.isPrototypeOf(b))return!1;return!0})});
$run(function(){function d(c){var b=arguments.callee;if(c instanceof b)return c;var a=typeof c;"string"==a?z._copy(b.__parse(c),this):"object"==a?z._copy(c,this):"function"==a&&(this.type=c);z._merge(arguments.callee.option,this)}eval($global.all);var e={required:"boolean",type:[Object,Array],ownProperty:"boolean",check:"function(o, name)",value:Object};d.option={required:!0,type:null,ownProperty:!1};d.__parse=function(c){var b={},a=c.match(/^\[(.*)\]$/);a&&(b.required=!1,c=a[1]);b.type=-1!=c.indexOf("|")?
c.split("|"):c;return b};d.prototype=$implement(e,{check:function(c,b){var a=c[b];if(null===a||void 0===a)return!this.required;if(this.type){var d=this.type;if($is(Array,d)){for(var e=!1,f=0,g=d.length;f<g;f++)if($is(d[f],a)){e=!0;break}if(!e)return!1}else if(!$is(d,a))return!1}return this.ownProperty&&!c.hasOwnProperty(b)?!1:!0}});$class(d).extend(z.Base);z.MemberSpec=d});
$run(function(){function d(b,a){var d={base:null,freeze:!1};d.type=a||Object;d.member=b;b.member&&(z._copy(b,d),d.type=b.type||Object);d.type&&(d.type=z.parseTypeSpec(d.type));var e=z.MemberSpec,f,g=d.member;for(f in g){var h=g[f];h instanceof e||(g[f]=new e(h))}$implement(c,d);return d}function e(b,a){if(!b.__implns__||-1==b.__implns__.indexOf(c))b=d(b);if(b.base&&!e(b.base,a)||b.type&&!$is(b.type,a))return!1;if(b.member){var j,i=b.member;for(j in i)if(!i[j].check(a,j))return!1;if(b.freeze){var f=
{};$trace(b,"base",function(a){z._merge(a.member,f)});for(j in a)if(!(j in f))return!1}}return!0}eval($global.all);var c=d({member:{base:"[object]",member:"[object]",type:z.ITypeSpec,freeze:"[boolean]"}});z.IInterface=c;$global("$protocol",d);$global("$support",e)});
$run(function(){eval($global.all);$global("$option",function(){var d=arguments,e=arguments.callee.caller,c=d[0]||e.arguments[0]||{},d=d[1]||e.option,b,a;for(b in d)e=d[b],a=typeof e,"object"==a?e.hasOwnProperty.required||(e.required=!1):"object"==a&&(d[b]={type:a,required:!1});b=$protocol(d);if($support(b,c)){b=b.member;for(var j in b)j in c||(c[j]=b[j].value);return c}throw"arguments invalid";})});
$run(function(){function d(c,b){var b=b||{},a=[],d,e,f,g;f=0;for(g=c.length;f<g;f++)d=c[f],e=typeof d,"function"==e?d.option?a.push({params:[Object],fn:d,useOption:!0}):a.push({params:[],fn:d,useOption:!1}):$is(Array,d)&&(e=d[1],$is(Array,e)?a.push({params:e,fn:d[0],useOption:!1}):z._isPlainObject(e)&&(d[0].option=d[1],a.push({params:[Object],fn:d[0],useOption:!0})));f=0;for(g=a.length;f<g;f++)d=a[f],e=d.params.length,b[e]||(b[e]=[]),b[e].push(d);return b}function e(c,b){var a=typeof b,d=typeof c;
if("string"!==d||"object"===c)if("object"===a||"function"===a){if($is(c,b))return!0}else{if({string:String,number:Number,"boolean":Boolean}[a]===c)return!0}else if(a==d)return!0;return!1}eval($global.all);$global("$overload",function(){var c=function(){var b=arguments,a;a:{a=b;if(b=b.callee.fnMap[a.length]){var c=a[0],d=1==a.length&&"object"===typeof c,f=0,g,h,n,l,k,f=0;for(g=b.length;f<g;f++)if(h=b[f],l=h.fn,k=h.params,h.useOption){if(d&&z._isPlainObject(c)&&(k=l.option,z._keys(k).length>=z._keys(c).length&&
$support(k,c))){a=l;break a}}else{var m=!0;h=0;for(n=k.length;h<n&&!(m=e(k[h],a[h]),!m);h++);if(m){a=l;break a}}}a=void 0}if(a)return a.apply(this,arguments)};c.fnMap=d(arguments);c.overload=function(b,a){if(b){var c=[];b&&a?c.push([b,a]):c.push(b);d(c,this.fnMap)}};return c})});
$run(function(){eval($global.all);var d={addListener:"function(event, listener)",on:"function(event, listener)",removeListener:"function(event, listener)",un:"function(event, listener)",getListerners:"function(event)",fire:"function(event, args)"},e=$module({onIncluded:function(){this.__listeners={};$implement(d,this)},on:this.addListener,addListener:function(c,b){var a=this.__listeners[c];a||(a=this.__listeners[c]=[]);a.push(b);return this},un:this.removeListener,removeListener:function(c,b){var a=
this.__listeners[c];if(a)return this.__listeners[c]=a.filter(function(a){return a!=b}),this},getListerners:function(c){return this.__listeners[c]},fire:function(c,b){this.getListerners(c).forEach(function(a){a(b)});return this}});z.MEvent=e});
$run(function(){eval($global.all);var d=$module({methods:function(){var d=this.allKeys(),c=this.target;return d.filter(function(b){return"function"==typeof c[b]})},publicMethods:function(){return this.methods().filter(function(d){return!z._isPrivate(d)})},privateMethods:function(){return this.methods().filter(function(d){return z._isPrivate(d)})},fields:function(){var d=this.allKeys(),c=this.target;return d.filter(function(b){return"function"!=typeof c[b]})},publicFields:function(){return this.fields().filter(function(d){return!z._isPrivate(d)})},
privateFields:function(){return this.fields().filter(function(d){return z._isPrivate(d)})},keys:function(){return Object.keys(this.target)},allKeys:function(){return z._keys(this.target)},type:function(){return typeof this.target},protoLink:function(){var d=[];z._traceProto(this.target,function(c){d.push(c)});return d},proto:function(){var d=this.target;return void 0!=={}.__proto__?d.__proto__:d.constructor.prototype},creator:function(){return this.target.constructor},implns:function(){var d=this.__implementions__;
return d?[]:d.slice(0)}});z.MInspect=d;$.regWrapper(d,Object,"MInspect");$global("$inspect",function(d){return $(d).wrapWith("MInspect")})});
